language: python
arch:
  - amd64
  - ppc64le

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.8"

# Build inside docker containers instead of virtual machines. These are
# faster, start quicker and support caching. Only downside: sudo is not
# supported.
sudo: false

# Dependencies can be installed as follows. This works only for packages
# whitelisted on https://github.com/travis-ci/apt-package-whitelist:
addons:
  apt:
    packages:
    - libkeyutils-dev

install:
  # Installation step for the python package itself:
  - pip install pytest
  - python setup.py install
  # Note, when running via py.test, we have to prevent importing keyutils from
  # current directory which doesn't contain the shared object:
  - rm -r keyutils

script:
  - py.test -v test/
